### ISSUE TITLE
rdflib_sqlalchemy.SQLAlchemy.SQLAlchemy.__repr__ tracebacks

### ISSUE THREAD

**Issue by dvarrazzo** [RDFLib/rdflib-sqlalchemy#10]
The `SQLAlchemy.__repr__` method raises an unhandled exception. A self-contained test:

    In [6]: import rdflib
    
    In [7]: x = rdflib.plugin.get('SQLAlchemy', rdflib.store.Store)(rdflib.URIRef("rdflib_test"))
    
    In [8]: print x
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-8-2d264e11d975> in <module>()
    ----> 1 print x
    
    /home/piro/src/rdfgambit/env/src/rdflib-sqlalchemy/rdflib_sqlalchemy/SQLAlchemy.pyc in __repr__(self)
        928                 None, ASSERTED_LITERAL_PARTITION), ]
        929         q = unionSELECT(selects, distinct=False, selectType=COUNT_SELECT)
    --> 930         with self.engine.connect() as connection:
        931             res = connection.execute(q)
        932             rt = res.fetchall()
    
    AttributeError: 'SQLAlchemy' object has no attribute 'engine'

**Comment by gjhiggins** [comment]
Fixed in commit 20fbf1fbbdbc53917bfd7554f38d22d08e71e225
