### ISSUE TITLE
Pg8000 and non-mapped type

### ISSUE THREAD

**Issue by blokhin** [RDFLib/rdflib-sqlalchemy#12]
Good day!
Is pg8000 Python driver for postgres supported?

I have errors like these, due to non-mapped type of @prefix xsd: <http://www.w3.org/2001/XMLSchema#> in my RDF:

File "pg8000/core.py", line 1885, in make_params
    "not mapped to pg type")

sqlalchemy.exc.NotSupportedError: (pg8000.core.NotSupportedError) type <class 'rdflib.term.URIRef'>not mapped to pg type [SQL: u'INSERT INTO kb_bec6803d52_literal_statements (subject, predicate, object, context, termcomb, objlanguage, objdatatype) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'http://example.com/penid1109001', u'http://www.w3.org/1999/02/22-rdf-syntax-ns#ID', u'1109001', u'example', 9, None, rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#integer'))]

or

sqlalchemy.exc.NotSupportedError: (pg8000.core.NotSupportedError) type <class 'rdflib.term.URIRef'>not mapped to pg type [SQL: u'INSERT INTO kb_bec6803d52_literal_statements (subject, predicate, object, context, termcomb, objlanguage, objdatatype) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'ub1bL12C21', u'http://www.w3.org/2002/07/owl#minQualifiedCardinality', u'2', u'example2', 69, None, rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#nonNegativeInteger'))]

SQLAlchemy version is 1.0.6, RDFLib 4.2.1.

**Comment by gromgull** [comment]
I don't know :) 

Judging by the amount of activity in this repo, and the number of requests about rdflib-sqlalchemy we get on the mailinglist (i.e. almost none) I would guess that very little of rdflib-sqlalchemy is "supported" 

I'm sorry I cannot be more helpful :)

**Comment by gjhiggins** [comment]
There's no support _per se_ but I added it to the tests in commit: c8f7748. Seems to work.
