### ISSUE TITLE
Upload package to PyPI

### ISSUE THREAD

**Issue by c-w** [RDFLib/rdflib-sqlalchemy#13]
Would it be possible for you to upload this package to PyPI?

Currently there only is the out-dated [rdflib-sqlite](https://pypi.python.org/pypi/rdflib-sqlite/0.1) package on PyPI. It would be great get this more up to date package up there too so that other projects can easily depend on rdflib-sqlalchemy.

**Comment by cpeel** [comment]
Agreed. We've recently updated the Gutenberg package to rely on this and are unable to upload it to PyPi because rdflib-sqlalchemy isn't up there.

**Comment by gjhiggins** [comment]
Done: https://pypi.python.org/pypi/rdflib-sqlalchemy/0.2.dev0

**Comment by gjhiggins** [comment]
@c-w thanks for the postcard!
