### ISSUE TITLE
Python3 import error with import sqlalchemy being thought of as a relative import on a Mac

### ISSUE THREAD

**Issue by cwilkes** [RDFLib/rdflib-sqlalchemy#16]
I'm using python 3.5 and when running `python setup.py build` I noticed that the import line `import sqlalchemy` from `rdflib_sqlalchemy/SQLAlchemy.py` was turned into `from . import sqlalchemy`

I tracked down the issue to the python module `lib2to3/fixes/fix_import.py` in the `probably_a_local_import` method that's passed in `sqlalchemy` to look for to see if it is a local import.  What happens is that it ends up checking to see if `build/src/rdflib_sqlalchemy/sqlalchemy.py` is a file.

Well this isn't really a file as `build/src/rdflib_sqlalchemy/SQLAlchemy.py` with different capitalization is one.  However by default macs are case INsensitive (yes, that's really annoying) and so `os.path.exists` will return True.

This is rather tricky as it means that you can't have a file with the same (lowercased) name of a module that you're importing when building your module.  Obviously later on people will be okay with it as they will do `import sqlalchemy` and `import rdflib_sqlalchemy.SQLAlchemy` and python recognizes those as two different modules.  I'm surprised this doesn't come up more often.

I'm not sure of the best way to go about fixing this.  Right now it is preventing me from using rdflib-sqlalchemy on a Mac.  I could turn it into a case sensitive file system but that doesn't help out someone else with the default.

Maybe there's a flag to setup.py that can be used to avoid this nonsense?

**Comment by adamhadani** [comment]
+1

**Comment by gjhiggins** [comment]
Fix kindly provided by Adam Ever-Hadani.

**Comment by g20ready** [comment]
I have version 0.3.8 installed an i am still getting 'No plugin registered for (SQLAlchemy, <class 'rdflib.store.Store'>)'. Is there any temporary fix?

**Comment by adamhadani** [comment]
@g20ready this is a separate error - There was some Python entry point-based plugin registration mechanism in `rdflib-sqlalchemy` when I started contributing to it which didn't seem to work to begin with. I removed that entry point altogether (but am open to re-introducing it if it's in wide-spread use).

FWIW, right now i'm instantiating it using something like the following. This is very modular so that is is easy to instantiate the SQLAlchemy engine separately from the rdflib store wrapper, and in turn from the actual rdflib Graph:

```python
from rdflib import Graph
from rdflib_sqlalchemy.store import SQLAlchemy
from sqlalchemy import create_engine

engine = create_engine(...)
identifier = URIRef("http://my.graph.namespace/")
store = SQLAlchemy(
    identifier=identifier,
    engine=engine,
)
graph = Graph(
    store,
    identifier=identifier,
),
```

If this is an issue for you even given the above, let's create a new GitHub Issue to track.

**Comment by TaihuaLi** [comment]
@adamhadani I have the PluginException: No plugin registered for (SQLAlchemy, <class 'rdflib.store.Store'>) issue too with Python 2.7.  However, I'm not using rdflib. I'm using the Gutenberg package (https://github.com/c-w/Gutenberg). 

Not sure how to fix this but is there a way to set up the plugin?
