### ISSUE TITLE
Create a new release, consider switching to use git-flow conventions for development

### ISSUE THREAD

**Issue by adamhadani** [RDFLib/rdflib-sqlalchemy#18]
Specifically:
What would be involved currently in tagging and pushing to PyPI a new versioned release of the project after recent merge of my previous PR #17 ?

More generally, I noticed the repository does not make use of git tags or branches to track released versions or automatically deploy tagged releases to PyPI. 

I'd like to suggest adopting the widely-used [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) convention (and associated [CLI tool](https://github.com/petervanderdoes/gitflow-avh)) for managing this going forward.

TL;DR this means:
- all ongoing development happens in 'develop' branch
- 'master' branch always reflects latest released version to which hot fixes can be applied directly if needed
- individual feature work is done on feature/\* branches, and merged back to develop via PRs
- individual releases go through a release/\* branch and get a git tag. This makes it easy to jump between different released versions, apply hotfixes and maintain ongoing development branch. 

Further, this model allows for easy release to PyPI - once a release is tagged and merged to master, we can define branch-specific CI logic that will build distributable and deploy it to PyPI (using something like this: https://docs.travis-ci.com/user/deployment/pypi/)

**Comment by adamhadani** [comment]
ping @gjhiggins for your kind consideration!

**Comment by adamhadani** [comment]
ping @gjhiggins any way for us to chat about this quickly? I'd love to get a release out with my recent PRs merged, and also have a suggestion per the above for how to make releasing easier going forward

**Comment by adamhadani** [comment]
ping @gjhiggins FYI I ended up forking this project here: https://github.com/globality-corp/rdflib-sqlalchemy , made some more progress with cleanup and removing of unused pieces (for reference: https://github.com/RDFLib/rdflib-sqlalchemy/compare/master...globality-corp:develop). if you have some time and interest going forward I'd be happy to merge it back to this repository and actively maintain here

**Comment by gromgull** [comment]
@adamhadani as you've noticed, this particular project isn't that well maintained. If you would like to step up and do it more actively I am more than happy to give you access!

**Comment by adamhadani** [comment]
@gromgull happy to, how should we proceed?

**Comment by gromgull** [comment]
I was going to say "I'll give you write access to the project", but you already have :) 

I also see that I don't own the pypi package - @gjhiggins does. I don't know if pypi lets several people have access to a package?

**Comment by adamhadani** [comment]
@gromgull / @gjhiggins I think I need the following things (which I don't have right now) -

1. Access to configure Travis CI (i'd like to use it with the git-flow conventions mentioned above so can automatically release package version using Travis CI's PyPI integration, based on git-flow release workflow)
2. Access to PyPI package account so can make new releases
3. Ability to manage (create/update/delete) branches on the repo (not sure if i have enough privileges currently to do this vs. just merging in pull requests)

**Comment by gromgull** [comment]
@adamhadani I've added you to the rdflib organisation (you should have an invite), this should be enough for you to setup travis as you wish, and maybe also create branches?

PyPi belongs to @gjhiggins, so has to give you access there.

**Comment by gjhiggins** [comment]
Many apologies, the fact that I had Pypi access totally dropped out of my memory, I had no recall of the act of publishing so thanks gromgull for prompting me directly. Fortunately, keepassx recalled the PyPi a/c details and the Pypi web form didn't object to me adding “adamhadani” as owner of rdflib-sqlalchemy. I assume (possibly over-optimistically) that the user a/c exists and is appropriately associated with the adamhadani posting here.

(Apologies also for failing to respond, Adam. props to you for it making no difference, sorry if I have put you to unnecessary inconvenience)

Cheers,
Graham

**Comment by adamhadani** [comment]
@gjhiggins no worries, thanks for picking up on this thread! I can confirm I have access to the PyPI package

@gromgull  - one request, it seems like I don't have access to the settings tab for the rdflib-sqlalchemy repo - I'd like to go ahead and make some changes to the branch settings (specifically make 'develop' the default branch, and then enable GitHub's Protected Branches feature so that it at least requires Travis CI tests to pass before any merges to develop) - Anyway I can get your help on making those changes (not sure if it's possible to grant me permissions that would allow me do it without giving me more permissions across the rdflib org which I imagine you would not want to do so quickly.. :)

**Comment by gromgull** [comment]
@adamhadani you're now admin!

Thanks a lot for picking this up! If you feel like taking a more active role in core rdflib development as well, just let me know ;)

**Comment by adamhadani** [comment]
thanks @gromgull will do!
