### ISSUE TITLE
SQLAlchemy.close() (and open()) fails

### ISSUE THREAD

**Issue by sztamas** [RDFLib/rdflib-sqlalchemy#24]
The close method tries to close the engine before setting it to ``None``.

https://github.com/RDFLib/rdflib-sqlalchemy/blob/0.3.5/rdflib_sqlalchemy/store.py#L623

However, the ``Engine`` class in SQLAlchemy doesn't have a ``close()`` method so an exception is raised.

**Comment by adamhadani** [comment]
@sztamas I fixed this in the above referenced feature branch, for the record - it doesn't seem to specify what kind of Exception should be raised so i went with the pretty generic RuntimeError - do you know anything more specific ? e.g other stores use anything standard?

**Comment by sztamas** [comment]
Thanks for fixing it!

Looking at the RDFLIB sleepycat implementation I have the feeling that throwing an exception wasn't really by design, the underlying code just threw one if the ``db.DB_CREATE`` flag wasn't set when opening the DB so they have added that to the documentation.
So, I think ``RuntimeError`` is fine.

Also, your open method (in your fix) does return ``None``.
I think that even if you don't go the trouble of returning all possible values like ``NO_STORE``, and ``CORRUPTED_STORE`` you should at least return ``VALID_STORE`` if all went well.

**Comment by adamhadani** [comment]
@sztamas - merged, open should return VALID_STORE as expected: https://github.com/RDFLib/rdflib-sqlalchemy/blob/develop/rdflib_sqlalchemy/store.py#L604

**Comment by sztamas** [comment]
OK, great!

Cheers,

Tamas
