### ISSUE TITLE
mysql connections might not be closed

### ISSUE THREAD

**Issue by jcjview** [RDFLib/rdflib-sqlalchemy#26]
When I use rdflib-sqlalchemy(0.3.8 ) with mysql , the connections will increase to 200+, and will still increase until python gc.

I watch the code,  and found  "self.engine = None" in class SQLAlchemy(story.py line 256).I believe this might cause this situation.

**Comment by jcjview** [comment]
I del graph and the connections close.

**Comment by adamhadani** [comment]
@jcjview thanks for the report, would it be possible for you to try out the version of the library in this PR to see if fixes the issue? https://github.com/RDFLib/rdflib-sqlalchemy/pull/28

**Comment by jcjview** [comment]
thanks ,i add  store.engine.dispose() before close().Now seems no connections leak .
