### ISSUE TITLE
create_engine kwargs is empty

### ISSUE THREAD

**Issue by jcjview** [RDFLib/rdflib-sqlalchemy#27]
And in  (story.py line 235). "self.engine = sqlalchemy.create_engine(configuration)", for "create_engine(*args, **kwargs)" configuration should be in second arg "kwargs"?

**Comment by adamhadani** [comment]
@jcjview  will enjoy your thoughts on the PR that fixes this, tried to make it backward-compliant as it must still comply with the open() interface dictated by the top-level `rdflib` project: https://github.com/RDFLib/rdflib-sqlalchemy/pull/29
