### ISSUE TITLE
using unlogged table feature in postgres

### ISSUE THREAD

**Issue by sandeep-gh** [RDFLib/rdflib-sqlalchemy#30]
Hi,
 
 We are trying to use this with postgres as the underlying data engine. 
 The RDF data we have is quite large and is taking a bit of time to get loaded.

 Was wondering if there is anyway we can control the backend table to be created
as a unlogged table in postgres. 

thanks.
sandeep

**Comment by adamhadani** [comment]
@sandeep-gh sounds like might be related to https://github.com/RDFLib/rdflib-sqlalchemy/issues/9 , e.g. we have a lot of intermittent commits ? have you tried setting sqlalchemy logging to verbose to see some of the SQL output when putting in data? e.g. using something like `logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)` early in your script?

**Comment by sandeep-gh** [comment]
Thanks Adam. Yes it was that issue. I now using addN. I also managed to force rdflib-sqlalchemy to create  unlogged table by explicitly adding a prefix directive in the tables.py, i.e., all tables are unlogged by default. If there is interest I can report the logged vs. unlogged time.

**Comment by mwatts15** [comment]
Closing this since it seems like @sandeep-gh's issue is resolved. I will note that modifications to the tables to enable vendor-specific features should be possible after the tables are created using vendor-specific tools or using sqlalchemy with the appropriate dialect.
