### ISSUE TITLE
entry_points removal and plugin registration issue

### ISSUE THREAD

**Issue by aleray** [RDFLib/rdflib-sqlalchemy#31]
Hi,

I did a project depending on rdflib-sqlalchemy in the past. Recently, I updated rdflib-sqlalchemy and started to have troubles, getting the message:

    PluginException: No plugin registered for (SQLAlchemy, <class 'rdflib.store.Store'>)

It seems to have to do with entry_points removal in `setup.py` which from what I got is a mechanism to auto-register plugins. I could trace back in the commit 7ce97561.

I'm not familiar at all with entry_points. Could you confirm it is related? Is there a new procedure to register the plugin?

Thanks.

**Comment by Murthy10** [comment]
I had the same troubles, unfortunately the API documentation is not helpful.

For me the following lines of code helped:

```
from rdflib import plugin, Graph, Literal, URIRef

from rdflib.store import Store
from rdflib_sqlalchemy import registerplugins

registerplugins()

identifier = URIRef("benchmark")
db_uri = Literal('postgresql+psycopg2://postgres:mysecretpassword@localhost:5432/benchmark')

store = plugin.get("SQLAlchemy", Store)(identifier=identifier, configuration=db_uri)
graph = Graph(store).parse('dataset.ttl', encoding='utf-8', format='n3')
graph.close()
```

The important part is ```registerplugins()```

**Comment by mwatts15** [comment]
Plugin registration was added back, so this should be resolved.
