### ISSUE TITLE
Add mwatts to PyPi maintainers

### ISSUE THREAD

**Issue by gjhiggins** [RDFLib/rdflib-sqlalchemy#49]
In abeyance, pending confirmation / advice of pypi username (perhaps https://pypi.org/user/MarkWatts/)?

**Comment by mwatts15** [comment]
Thanks, @gjhiggins . Here's me: https://pypi.org/user/markw/

**Comment by gjhiggins** [comment]
Resolved, added markw as PyPi co-owner.
