### ISSUE TITLE
How do I load this plugin?

### ISSUE THREAD

**Issue by sharpaper** [RDFLib/rdflib-sqlalchemy#60]
Hi! I'd like to use this plugin to persist an rdflib graph into sqlite. Unfortunately I do not understand how to load this plugin. In the README there is only a test class that I don't fully understand. Could you please add an example to show how to use the plugin with rdflib?

Thank you a lot for making this plugin.

**Comment by sharpaper** [comment]
In particular I get this error: `rdflib.plugin.PluginException: No plugin registered for (SQLAlchemy, <class 'rdflib.store.Store'>)` and I don't really understand how to fix this.

**Comment by mwatts15** [comment]
Hi, @sharpaper . You have to install rdflib-sqlalchemy (e.g., `pip install rdflib-sqlalchemy`) in order for RDFLib to be able to find it.

**Comment by sharpaper** [comment]
And execute `registerplugins()`?

**Comment by mwatts15** [comment]
It should not be necessary to execute registerplugins manually. There is an
entry point defined which rdflib should query to do the registration.

**Comment by davidshumway** [comment]
On Google Colab, the following occurs:

```python
!pip install rdflib-sqlalchemy rdflib
import rdflib
rdflib.Graph(store='SQLAlchemy')
```

Causes the following error:

> KeyError: ('SQLAlchemy', <class 'rdflib.store.Store'>)

Perhaps this is just a Colab issue?

**Comment by davidshumway** [comment]
```python
!pip install rdflib-sqlalchemy rdflib
from rdflib import plugin, Graph, Literal, URIRef
from rdflib.store import Store
store = plugin.get("SQLAlchemy", Store)
```

> KeyError: ('SQLAlchemy', <class 'rdflib.store.Store'>)

**Comment by davidshumway** [comment]
Restarting the runtime apparently fixed the issue. Either that or it was fixed due to installing oxrdflib and then restarting the runtime?? (`pip install oxrdflib`)

**Comment by mwatts15** [comment]
Not sure how that platform works, but you generally restart the Python
runtime after installing with pip. You can get around that by modifying
sys.path after the install (or probably with some importlib magic).
