### ISSUE TITLE
Is "klass" a typo?

### ISSUE THREAD

**Issue by sharpaper** [RDFLib/rdflib-sqlalchemy#61]
Should `klass` be `class` instead?

https://github.com/RDFLib/rdflib-sqlalchemy/blob/abe20884d2450106ce89805c8c837d670be1622c/rdflib_sqlalchemy/tables.py#L76

**Comment by mwatts15** [comment]
Hi, @sharpaper. No, the use of `klass` is intentional. You will see it throughout the code. Since columns can be accessed as attributes (see base.py) and `class` is a reserved word, the convention of `klass` was chosen to avoid that conflict.
