### ISSUE TITLE
Working with MySQL, getting random "Specified key was too long; max key length is 3072 bytes" error

### ISSUE THREAD

**Issue by Etienne-T** [RDFLib/rdflib-sqlalchemy#67]
I am new to rdflib-sqlalchemy and I try to use it with MySQL.
I am currently running
rdflib 5.0.0
rdflib-sqlalchemy 0.4.0
SQLAlchemy 1.3.9
mysql-connector-python 8.0.21

By simply trying to create a graph in the database it results most of the time in the following error:
**sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 3072 bytes')
[SQL: CREATE UNIQUE INDEX kb_efa2ab3084_quoted_spoc_key ON kb_efa2ab3084_quoted_statements (subject(200), predicate(200), object(200), objlanguage(200), context(200))]**

What is really strange is that sometimes, the creation works and the error does not show.
Any suggestions ?

Regards,
Etienne

**Comment by mwatts15** [comment]
Hi, @Etienne-T. What version of MySQL are you using? If you can, please also provide a piece of example code that reproduces your issue.

**Comment by mwatts15** [comment]
Haven't gotten any response on this issue, so closing now. Please re-open or create a new issue if more information is available such as the requested version of MySQL or a consistent way to reproduce the issue.

**Comment by mwatts15** [comment]
I'm seeing this issue now on CI....I guess we need to store the values in their own table or remove some stuff from the index...

**Comment by mwatts15** [comment]
I've limited the size of the index on the develop branch
