### ISSUE TITLE
SQLAlchemy-1.4.0-cp37-cp37m-win_amd64.whl

### ISSUE THREAD

**Issue by rchateauneu** [RDFLib/rdflib-sqlalchemy#71]
There is apparently a problem with rdflib_sqlalchemy-0.4.0-py3-none-any.whl and the new version of SQLAlchemy-1.4.0-cp37-cp37m-win_amd64.whl compared to SQLAlchemy-1.3.23-cp37-cp37m-win_amd64.whl

My tests running on Travis used to work until yesterday https://travis-ci.com/github/rchateauneu/survol/jobs/491016928 and they are broken with the latest SQLAlchemy-1.4.0 version : Same problems with Linux Python 2 and 3, and Windows Python 3.

All the other packages loaded by TravisCI are the identical except this dependency.

One of the errors is for example:
```
        for table, whereClause, tableType in select_components:

            if select_type == COUNT_SELECT:
>               select_clause = table.count(whereClause)
E               AttributeError: 'Alias' object has no attribute 'count'
c:\python37\lib\site-packages\rdflib_sqlalchemy\sql.py:56: AttributeError
```

Thanks

**Comment by rchateauneu** [comment]
More information and the suggestion of a fix here:
https://github.com/sqlalchemy/sqlalchemy/issues/6053

**Comment by mwatts15** [comment]
Thanks for the report. Looks pretty straight forward. I should have a fix
sometime this week. Patches welcome though.

**Comment by rchateauneu** [comment]
I sent a pull request. It might not be perfect (Not much experience of SQLAlchemy) but it runs the tests.
