### ISSUE TITLE
Extra "test" subdirectory in tests ?

### ISSUE THREAD

**Issue by rchateauneu** [RDFLib/rdflib-sqlalchemy#72]
Starting investigate this issue https://github.com/RDFLib/rdflib-sqlalchemy/issues/71 , in this fork https://github.com/rchateauneu/rdflib-sqlalchemy/tree/SQLAlchemy_1_4_Count, and running tests, I was wondering if some "test" subdirectories specified in some scripts are needed or not ?

test/test_aggregate_graphs.py
```
self.graph4.parse('test/rdf-schema.n3', format='n3')
```

test/test_store_performance.py
```
inputloc = os.getcwd() + '/test/sp2b/%s.n3' % i
self.path = "sqlite:///%(here)s/test/tmpdb.sqlite" % {
            "here": os.getcwd()
        }
```

I have to remove these "test/", in order to be able to run the tests with pytest, like this:
```
pytest -v test
```

Did I do something wrong ? Thanks.

**Comment by mwatts15** [comment]
The tests should be run with the project root directory as the working directory
