### ISSUE TITLE
Drop support for old Python versions

### ISSUE THREAD

**Issue by mwatts15** [RDFLib/rdflib-sqlalchemy#73]
Python 2.7 has been deprecated since last year, and it's increasingly difficult to maintain this project on Python 2.7, so it's past time to stop supporting it. Support for Python versions earlier than 3.6 will also be dropped as they have also reached EOL.

**Comment by rchateauneu** [comment]
Ideally, I need Python 2,7 (Still used a lot on Linux) and I can help supporting it, if needed.

**Comment by mwatts15** [comment]
@rchateauneu that's why I made this issue :) I don't think that will work out long-term, and I don't promise any special effort to keep Python 2.7 working, but I can try to avoid breaking compatibility and merge PRs to keep it working...for at least a year. Beyond that, I'd ask you to take over maintenance of this package as a whole because keeping Python 2.7 compat _will_ become untenable with the time I have.

**Comment by rchateauneu** [comment]
Thanks to warn in advance. Indeed py2.7 will gradually disappear but before that, I will be happy to help if needed.

**Comment by mwatts15** [comment]
@rchateauneu FYI, I'll be adding py27 labels for issues that come up which are specific to Python2.7

**Comment by mwatts15** [comment]
@rchateauneu are you still intending to support Python 2.7? I was expecting some action on py27 issues like this one https://github.com/RDFLib/rdflib-sqlalchemy/issues/76 .

**Comment by mwatts15** [comment]
Python 2.7 is no longer supported, so closing this.
