### ISSUE TITLE
Engine.has_table() method is deprecated

### ISSUE THREAD

**Issue by rchateauneu** [RDFLib/rdflib-sqlalchemy#78]
There seems to be a future deprecation in SQLAlchemy because I get this warning:

```
python3.8/site-packages/rdflib_sqlalchemy/store.py:762: SADeprecationWarning: The Engine.has_table() method is deprecated and will be removed in a future release.  Please refer to Inspector.has_table(). (deprecated since: 1.4)
    if not self.engine.has_table(table_name):
```

It is apparently replaced by this:
```
[Reflecting Database Objects Inspector.has_table](https://docs.sqlalchemy.org/en/14/core/reflection.html#sqlalchemy.engine.reflection.Inspector.has_table)
```

Many thanks.

PS: Also, when will be the next release, please ?? Thanks !

**Comment by mwatts15** [comment]
@rchateauneu I'll try for some time in the next two weeks. I think for a release schedule, I could do twice a year, but more frequently for more urgent issues.
