### ISSUE TITLE
addN returns how many triples were actually added?

### ISSUE THREAD

**Issue by bazile-clyde** [RDFLib/rdflib-sqlalchemy#81]
So I understand that `addN` ignores-on-conflict for any duplicate triples (at least with psycopg2). Are there any methods that return the number of triples that were actually inserted into the database? Could this functionality be added? It'd be nice to know if this function was simply a no-op or not.

**Comment by mwatts15** [comment]
I did make a [PR](https://github.com/RDFLib/rdflib/pull/834) for this a while ago on rdflib/rdflib. You can try to rehab it if you want.

**Comment by bazile-clyde** [comment]
> I did make a [PR](https://github.com/RDFLib/rdflib/pull/834) for this a while ago on rdflib/rdflib. You can try to rehab it if you want.

@mwatts15 Thanks! Ah, I see. It looks like I'll have to update the interface through RDFLib first. Closing this.
