### ISSUE TITLE
Loading a large ontology using PostgreSQL as the backend results in BTREE index error

### ISSUE THREAD

**Issue by chris-day** [RDFLib/rdflib-sqlalchemy#82]
When I try to load a large ontology such as CHEBI (https://bioportal.bioontology.org/ontologies/CHEBI) I get a BTREE error with PostgreSQL. As mitigation, I disabled the index creation.

**Comment by rchateauneu** [comment]
Hi Chris,
Is it please possible to have a small script reproducing the error ?
Thanks in advance.

**Comment by mwatts15** [comment]
Closing as requested repro was never provided.
