### ISSUE TITLE
How to query the database?

### ISSUE THREAD

**Issue by bazile-clyde** [RDFLib/rdflib-sqlalchemy#83]
It looks like the store doesn't implement the `query` method. So calling `query` on a graph using RDFLib-SQLAlchemy as a store throws a `NotImplementedError`.

**Comment by mwatts15** [comment]
@bazile-clyde, please provide a code example showing what you've tried. The Store doesn't have to implement query for you to do SPARQL queries since the Graph will use the sparql plugin to parse the query and translate into calls to `triples` and `triples_choices'

**Comment by bazile-clyde** [comment]
@mwatts15 Ah that answers my question. Stepping through the code, I wondered why the store kept throwing a `NotImplementedError` when I queried the graph. But as you stated, it just ends up calling the query method from the SPARQL plugin. Thanks!
