### ISSUE TITLE
Performance warning

### ISSUE THREAD

**Issue by renefritze** [RDFLib/rdflib-sqlalchemy#91]
I've just started experimenting with 
rdflib-sqlalchemy and I get this warning:

```
 /usr/local/lib/python3.9/site-packages/rdflib_sqlalchemy/store.py:333: SAWarning: 
Class OnConflictDoNothing will not make use of SQL compilation caching as it does not set the 'inherit_cache' 
attribute to ``True``.   This can have significant performance implications including some performance 
degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make 
use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which 
will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
```

Is this actually significant or can it be ignored?
This is with 
```
SQLAlchemy==1.4.36
rdflib==6.1.1
rdflib-sqlalchemy==0.5.1
```

**Comment by renefritze** [comment]
Can anybody comment on this?

**Comment by mwatts15** [comment]
Hi. I see this, but I'm not sure how important it is yet. Looks like it's specific to postgres. I don't have time to research it just now. If you can do some research on it and make a recommendation (or a pull request) it can get resolved more quickly.

**Comment by renefritze** [comment]
I can certainly run some specific test you may have in mind. However I cannot invest significant research time into this issue either.

**Comment by mwatts15** [comment]
I'd say it's for SQLAlchemy to have `inherit_cache` set on `OnConflictDoNothing` and/or define cache ID generation. So, this is an issue for SQLAlchemy.

If the warning bothers you, you can ignore it with this:
```
                    warnings.filterwarnings(
                        "ignore",
                        ".*Class OnConflictDoNothing will not make use of SQL compilation caching.*",
                    )
```

**Comment by mwatts15** [comment]
Thanks for the report. That's a new one on me. I'll look into it soon.
